{
  parserClass="de.uniorg.ui5helper.binding.BindingParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Simple"
  psiImplClassSuffix="Impl"
  psiPackage="de.uniorg.ui5helper.binding.psi"
  psiImplPackage="de.uniorg.ui5helper.binding.psi.impl"

  elementTypeHolderClass="de.uniorg.ui5helper.binding.psi.BindingTypes"
  elementTypeClass="de.uniorg.ui5helper.binding.psi.BindingElementType"
  tokenTypeClass="de.uniorg.ui5helper.binding.psi.BindingTokenType"

  psiImplUtilClass="de.uniorg.ui5helper.binding.psi.impl.BindingParserImplUtil"
}

value ::= item_*

private item_ ::= (binding|STRING)

binding ::= (CURLY_OPEN (STRING MODEL_SEP)? PATH_SEP? (STRING PATH_SEP)* STRING? CURLY_CLOSE)